# Generated by Django 4.1.7 on 2023-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True)),
                ('k', models.ManyToManyField(blank=True, related_name='k_selected', to='nfldata.nfl_players')),
                ('k_backup', models.ManyToManyField(blank=True, related_name='k_backup_selected', to='nfldata.nfl_players')),
                ('qb', models.ManyToManyField(blank=True, related_name='qb_selected', to='nfldata.nfl_players')),
                ('qb_backup', models.ManyToManyField(blank=True, related_name='qb_backup_selected', to='nfldata.nfl_players')),
                ('rb', models.ManyToManyField(blank=True, related_name='rb_selected', to='nfldata.nfl_players')),
                ('rb_backup', models.ManyToManyField(blank=True, related_name='rb_backup_selected', to='nfldata.nfl_players')),
                ('te', models.ManyToManyField(blank=True, related_name='te_selected', to='nfldata.nfl_players')),
                ('te_backup', models.ManyToManyField(blank=True, related_name='te_backup_selected', to='nfldata.nfl_players')),
                ('wr', models.ManyToManyField(blank=True, related_name='wr_selected', to='nfldata.nfl_players')),
                ('wr_backup', models.ManyToManyField(blank=True, related_name='wr_backup_selected', to='nfldata.nfl_players')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
