# Generated by Django 4.2.1 on 2023-05-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('k', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_selected', to='nfldata.nfl_players')),
                ('k_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_backup_selected', to='nfldata.nfl_players')),
                ('qb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qb_selected', to='nfldata.nfl_players')),
                ('qb_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qb_backup_selected', to='nfldata.nfl_players')),
                ('rb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_selected', to='nfldata.nfl_players')),
                ('rb_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_backup_selected', to='nfldata.nfl_players')),
                ('te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='te_selected', to='nfldata.nfl_players')),
                ('te_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='te_backup_selected', to='nfldata.nfl_players')),
                ('wr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_selected', to='nfldata.nfl_players')),
                ('wr_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wr_backup_selected', to='nfldata.nfl_players')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('week_number',)},
            },
        ),
    ]
