# Generated by Django 4.1.7 on 2023-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFL_Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team', models.TextField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('jersey_number', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nfl_player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NFL_Stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_id', models.TextField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('player_display_name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('position_group', models.TextField(blank=True, null=True)),
                ('headshot_url', models.TextField(blank=True, null=True)),
                ('recent_team', models.TextField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('season_type', models.TextField(blank=True, null=True)),
                ('completions', models.IntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('passing_yards', models.FloatField(blank=True, null=True)),
                ('passing_tds', models.IntegerField(blank=True, null=True)),
                ('interceptions', models.FloatField(blank=True, null=True)),
                ('sacks', models.FloatField(blank=True, null=True)),
                ('sack_yards', models.FloatField(blank=True, null=True)),
                ('sack_fumbles', models.IntegerField(blank=True, null=True)),
                ('sack_fumbles_lost', models.IntegerField(blank=True, null=True)),
                ('passing_air_yards', models.FloatField(blank=True, null=True)),
                ('passing_yards_after_catch', models.FloatField(blank=True, null=True)),
                ('passing_first_downs', models.FloatField(blank=True, null=True)),
                ('passing_epa', models.FloatField(blank=True, null=True)),
                ('passing_2pt_conversions', models.IntegerField(blank=True, null=True)),
                ('pacr', models.FloatField(blank=True, null=True)),
                ('dakota', models.FloatField(blank=True, null=True)),
                ('carries', models.IntegerField(blank=True, null=True)),
                ('rushing_yards', models.FloatField(blank=True, null=True)),
                ('rushing_tds', models.IntegerField(blank=True, null=True)),
                ('rushing_fumbles', models.FloatField(blank=True, null=True)),
                ('rushing_fumbles_lost', models.FloatField(blank=True, null=True)),
                ('rushing_first_downs', models.FloatField(blank=True, null=True)),
                ('rushing_epa', models.FloatField(blank=True, null=True)),
                ('rushing_2pt_conversions', models.IntegerField(blank=True, null=True)),
                ('receptions', models.IntegerField(blank=True, null=True)),
                ('targets', models.IntegerField(blank=True, null=True)),
                ('receiving_yards', models.FloatField(blank=True, null=True)),
                ('receiving_tds', models.IntegerField(blank=True, null=True)),
                ('receiving_fumbles', models.FloatField(blank=True, null=True)),
                ('receiving_fumbles_lost', models.FloatField(blank=True, null=True)),
                ('receiving_air_yards', models.FloatField(blank=True, null=True)),
                ('receiving_yards_after_catch', models.FloatField(blank=True, null=True)),
                ('receiving_first_downs', models.FloatField(blank=True, null=True)),
                ('receiving_epa', models.FloatField(blank=True, null=True)),
                ('receiving_2pt_conversions', models.IntegerField(blank=True, null=True)),
                ('racr', models.FloatField(blank=True, null=True)),
                ('target_share', models.FloatField(blank=True, null=True)),
                ('air_yards_share', models.FloatField(blank=True, null=True)),
                ('wopr', models.FloatField(blank=True, null=True)),
                ('special_teams_tds', models.FloatField(blank=True, null=True)),
                ('fantasy_points', models.FloatField(blank=True, null=True)),
                ('fantasy_points_ppr', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nfl_weekly_stat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFL_Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_abbr', models.TextField(blank=True, null=True)),
                ('team_name', models.TextField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('team_nick', models.TextField(blank=True, null=True)),
                ('team_conf', models.TextField(blank=True, null=True)),
                ('team_division', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nfl_team',
                'managed': True,
            },
        ),
    ]
