# Generated by Django 4.1.7 on 2023-03-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflplayers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nflstats',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nflteams',
            options={'managed': True},
        ),
    ]
